### ISSUE TITLE
Change branch name to `main`

### ISSUE THREAD

**Issue by avinal** [lenargasimov/lenargasimov#1]
Hello @lenargasimov, I just stumbled across your repo and found this error. The branch name should be `main` because your default branch is `main`. 
https://github.com/lenargasimov/lenargasimov/blob/890f248211c78f3203066ef7adeec062a5bc8872/.github/workflows/main.yml#L23

**Comment by lenargasimov** [comment]
Hey! Thanks for pointing out the error! Have a nice day buddy!
